### ISSUE TITLE
attribute definitions in codeblock cause error

### ISSUE THREAD

**Issue by sefuhrer** [IBM/marked-it#14] opened 2019-10-23 23:25 UTC
While we can code examples of using attributes in html, and you will pass it straight through, we want to be able to ignore all values nested in ````` code blocks.

Example of a file with attributes in codeblocks:
[support-center.md.zip](https://github.com/IBM/marked-it/files/3764944/support-center.md.zip)

Error thrown: 

```
/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:1060
                start = match.index;
                              ^

TypeError: Cannot read property 'index' of null
    at computeBlocks (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:1060:19)
    at new Block (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:1203:20)
    at computeBlocks (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:1147:19)
    at new Block (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:1203:20)
    at computeBlocks (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:1147:19)
    at new Block (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:1203:20)
    at Object.generate (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/htmlGenerator.js:116:18)
    at Object.generate (/Users/Sebastian/node_modules/marked-it-cli/node_modules/marked-it-core/lib/marked-it.js:82:33)
    at generateHTML (/Users/Sebastian/node_modules/marked-it-cli/lib/mdProcessor.js:336:28)
    at Object.generate (/Users/Sebastian/node_modules/marked-it-cli/lib/mdProcessor.js:475:2)
```

**Comment by grant-g** [comment] 2024-09-04 14:10
Confirmed that this error no longer happens in the latest, likely due to the significant re-write that has happened in the meantime around md->HTML generation.  Closing Issue.

**Closed as completed by grant-g** 2024-09-04 14:10 UTC
